### ISSUE TITLE
Crash in urwid while deploying hadoop-processing

### ISSUE THREAD

**Issue by petevg** [juju-solutions/matrix#31]
I get this exception while running the default tests against hadoop-processing, in a branch where I've made some changes to the way that we do glitch actions ... I think that the changes are clearing up some other crashes and making it easier to see this crash, rather than causing it, though.

This leaves urwid in a state where it no longer updates, meaning that we can't finish the deploy action.
[matrix.log.zip](https://github.com/juju-solutions/matrix/files/627535/matrix.log.zip)

```
matrix:354:exception_handler: Exception in callback AsyncioEventLoop.enter_idle.<locals>.faux_idle_callback() at /home/petevg/Code/matrix/.tox/py35/lib/python3.5/site-packages/urwid/main_loop.py:1288
matrix:358:exception_handler: Traceback (most recent call last):

  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)

  File "/home/petevg/Code/matrix/.tox/py35/lib/python3.5/site-packages/urwid/main_loop.py", line 1289, in faux_idle_callback
    callback()

  File "/home/petevg/Code/matrix/.tox/py35/lib/python3.5/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()

  File "/home/petevg/Code/matrix/.tox/py35/lib/python3.5/site-packages/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)

  File "/home/petevg/Code/matrix/.tox/py35/lib/python3.5/site-packages/urwid/raw_display.py", line 838, in draw_screen
    l = l.decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: unexpected end of data
```

**Comment by petevg** [comment]
Here's a dump of the array of byte strings that we're trying to output. It looks like maybe we're treating the byte strings like a list at some point, leading to little orphaned byte strings that can't actually be decoded. Not sure quite where we're doing it, though: 
[dump.zip](https://github.com/juju-solutions/matrix/files/627803/dump.zip)

**Comment by petevg** [comment]
Fixed by @johnsca's PR :-)
