### ISSUE TITLE
Crash while destroying a model on AWS

### ISSUE THREAD

**Issue by petevg** [juju-solutions/matrix#70]
This happened in the cwr charm. Looks like we got a timeout trying to tear down the model, which means that a) our second test never ran, and b) we left a model shaped mess on the controller.

```
                                
                                                                            matrix:124:load_suites: Parsing /usr/local/lib/python3.5/dist-packages/matrix/matrix.yaml
matrix:422:add_model: Creating model matrix-fun-chimp
Start Test deployment Basic Deployment
==============================================================================
deploy:4:deploy: Deploying /tmp/cwr-tmp-ViPWhT/bundletester-HKYRI6/cs__kwmonroe_bundle_java_devenv
deploy:6:deploy: Deploy COMPLETE
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: busy
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: settling
health:56:health: Health check: healthy
------------------------------------------------------------------------------
matrix:228:crashdump: Running crash dump
matrix:230:crashdump: Crashdump specified, but skipping juju-crashdump due to gh issue #59. Will still save off matrix log.
matrix:263:crashdump: Crashdump COMPLETE
matrix:461:destroy_model: Destroying model matrix-fun-chimp
matrix:403:run: Error destroying model: 
matrix:490:exception_handler: Top Level Exception Handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
asyncio:1148:default_exception_handler: Unhandled error in exception handler
context: {'message': 'Fatal read error on socket transport', 'exception': TimeoutError(110, 'Connection timed out'), 'transport': <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>, 'protocol': <asyncio.sslproto.SSLProtocol object at 0x7ff0e5122240>}
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1180, in call_exception_handler
    self._exception_handler(self, context)
  File "/usr/local/lib/python3.5/dist-packages/matrix/rules.py", line 498, in exception_handler
    raise e
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
matrix:490:exception_handler: Top Level Exception Handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
asyncio:1148:default_exception_handler: Unhandled error in exception handler
context: {'message': 'Fatal read error on socket transport', 'exception': TimeoutError(110, 'Connection timed out'), 'transport': <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>, 'protocol': <asyncio.sslproto.SSLProtocol object at 0x7ff0e3291fd0>}
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1180, in call_exception_handler
    self._exception_handler(self, context)
  File "/usr/local/lib/python3.5/dist-packages/matrix/rules.py", line 498, in exception_handler
    raise e
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
matrix:378:run: Error adding model: WebSocket connection is closed: code = 1006, no reason.
------------------------------------------------------------------------------
matrix:228:crashdump: Running crash dump
matrix:230:crashdump: Crashdump specified, but skipping juju-crashdump due to gh issue #59. Will still save off matrix log.
matrix:263:crashdump: Crashdump COMPLETE
matrix:461:destroy_model: Destroying model matrix-fun-chimp
matrix:403:run: Error destroying model: WebSocket connection is closed: code = 1006, no reason.
Run Complete
deployment         ✔
end_to_end         ✘
```

**Comment by petevg** [comment]
This has been addressed with a loop in the cleanup routine in rules.py.
